version: '3.8'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - web

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`XXXXXX`)"                       # <---- Replace with own domain
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.tls=true"


  backend:
    container_name: backend
    build: ./backend
    env_file:
      - backend/.env
    depends_on:
      - postgres
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=backendport"
      - "traefik.http.routers.backend.rule=Host(`XXXXXXX`)"                       # <---- Replace with own domain
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.tls=true"

  traefik:
    container_name: traefik
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.pgadminport.address=:8000"
      - "--entrypoints.backendport.address=:8443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=yourMail@example.com"      # <---- Replace with own mail
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@newtec.de
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - web
    labels:
      - "traefik.http.routers.pgadmin.entrypoints=pgadminport"
      - "traefik.http.routers.pgadmin.rule=Host(`speiseplan-nt.informatik.uni-ulm.de`)"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.routers.pgadmin.tls=true"

networks:
  web:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  letsencrypt:
    driver: local
