version: '3.8'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@newtec.de
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres:
  pgadmin:
