site_name: Dokumentation Speiseplan NewTec
nav:
  - Getting Started: index.md
theme:
  name: material
  favicon: imgs/favicon.ico
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables